Revert "simplify osrs image sync script"
This reverts commit 292150d14aad7c3cbdcef705d3ab4f435fa402ae.

diff --git a/bin/vps_sync_osrs_images b/bin/vps_sync_osrs_images
--- a/bin/vps_sync_osrs_images
+++ b/bin/vps_sync_osrs_images
@@ -1,15 +1,33 @@
 #!/usr/bin/env bash
-# sync osrs images to cache, then to remote server
-
-set -euo pipefail
+# sync osrs images to cache while optimizing, then sync to remote server
 
 echo 'Syncing OSRS images to server...' >&2
 
-rsync -Pah --ignore-existing "$HPIDATA/runelite_screenshots" "$HOME/.cache"
+# make sure user has optimg
+if ! command -v optipng &>/dev/null; then
+	echo "optipng could not be found" >&2
+	exit 1
+fi
 
-# to optimize, run:
-# cd ~/.cache/runelite_screenshots/
-# list-images | parallel -k --eta -j+0 optipng -o 5 {}
+cd "$HPIDATA" || exit
+
+if [[ ! -d runelite_screenshots ]]; then
+	echo "runelite_screenshots folder not found" >&2
+	exit 1
+fi
+
+# sync from $FROM to ~/.cache/runelite_screenshots while optimizing
+while read -r line; do
+	target="$HOME/.cache/$line"
+	# skip if the file already exists
+	if [[ -f "$target" ]]; then
+		continue
+	fi
+	# mkdir, copy, then optimize
+	mkdir -p "$(dirname "$target")"
+	cp -pv "$line" "$target"
+	optipng -preserve -o5 "$target"
+done <<<"$(fd . runelite_screenshots -e png -t f)"
 
 # sync from ~/.cache/runelite_screenshots to remote server
 exec rsync -Pavhz "$HOME/.cache/runelite_screenshots" vultr:./static_files >/dev/null
