autoformat shell scripts

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -3,44 +3,43 @@
 
 # require that a executable be installed
 require() {
-  if [[ ! $(command -v "$1") ]]; then
-    printf "requires %s, Install that and re-run\n" "$1"
-    exit 1
-  fi
+	if [[ ! $(command -v "$1") ]]; then
+		printf "requires %s, Install that and re-run\n" "$1"
+		exit 1
+	fi
 }
 
 # mkdir if first arg doesnt exist
 mkdir_if_not_exists() {
-  if [ ! -d "$1" ]; then
-    mkdir -p "$1"
-  fi
+	if [ ! -d "$1" ]; then
+		mkdir -p "$1"
+	fi
 }
 
 # make sure a file exists or exit
 expect_file_and_copy() {
-  if [ ! -f "$1" ]; then
-    printf "Fatal error: Expected file at %s\n" "$1"
-    exit 1
-  fi
-  cp "$1" "$2"
+	if [ ! -f "$1" ]; then
+		printf "Fatal error: Expected file at %s\n" "$1"
+		exit 1
+	fi
+	cp "$1" "$2"
 }
 
 optional_copy() {
-  if [ -f "$1" ]; then
-    cp "$1" "$2"
-  else
-    printf "Warning: Expected file at %s\n" "$1"
-  fi
+	if [ -f "$1" ]; then
+		cp "$1" "$2"
+	else
+		printf "Warning: Expected file at %s\n" "$1"
+	fi
 }
 
 delete_if_exists() {
-  [[ -d "$1" || -f "$1" ]] && rm -rf "$1" && printf "Removed '%s'\n" "$1"
+	[[ -d "$1" || -f "$1" ]] && rm -rf "$1" && printf "Removed '%s'\n" "$1"
 }
 
 require tar
 require realpath
 require tree
-
 
 CUR_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
 cd "$CUR_DIR"
diff --git a/generate_static_sites b/generate_static_sites
--- a/generate_static_sites
+++ b/generate_static_sites
@@ -1,36 +1,36 @@
 #!/bin/bash
 
 # function to check if required commands exist prior to bootstrap
-require () {
-  if [[ ! $(command -v "$1") ]]; then
-    printf "requires '%s', Install that and re-run\n" "$1"
-    exit 1
-  fi
+require() {
+	if [[ ! $(command -v "$1") ]]; then
+		printf "requires '%s', Install that and re-run\n" "$1"
+		exit 1
+	fi
 }
 
 # $1: url, $2: location
 reclone_dir() {
-  [ -d "$2" ] && rm -rf "$2"
-  git clone --depth=1 --branch=master "$1" "$2"
-  rm -rf "$2/.git"
+	[ -d "$2" ] && rm -rf "$2"
+	git clone --depth=1 --branch=master "$1" "$2"
+	rm -rf "$2/.git"
 }
 
 # removes any files currently in the REMOVE_FILES array
 remove_files() {
-  for remove_file in "${REMOVE_FILES[@]}"; do
-    rm -vrf "$remove_file"
-  done
+	for remove_file in "${REMOVE_FILES[@]}"; do
+		rm -vrf "$remove_file"
+	done
 }
 
 # $1: static site folder to move to document root root
 move_to_document_root() {
-  TARGET="${DOCUMENT_ROOT}/$(basename "$1")"
-  if [ -d "$DOCUMENT_ROOT" ]; then
-    sudo rm -rf "$TARGET"
-    sudo mv -v "$1" "$DOCUMENT_ROOT"
-  else
-    printf "Error moving files: '%s' does not exist.\n" "$DOCUMENT_ROOT"
-  fi
+	TARGET="${DOCUMENT_ROOT}/$(basename "$1")"
+	if [ -d "$DOCUMENT_ROOT" ]; then
+		sudo rm -rf "$TARGET"
+		sudo mv -v "$1" "$DOCUMENT_ROOT"
+	else
+		printf "Error moving files: '%s' does not exist.\n" "$DOCUMENT_ROOT"
+	fi
 }
 
 require git
@@ -39,7 +39,7 @@ require make
 require python3
 require realpath
 
-CUR_DIR="$(realpath "$( dirname "${BASH_SOURCE[0]}" )")"
+CUR_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
 BUILD_DIR="${CUR_DIR}/static_build"
 
 DOCUMENT_ROOT="/var/www/html"
diff --git a/vps_install b/vps_install
--- a/vps_install
+++ b/vps_install
@@ -2,42 +2,42 @@
 
 # cd to a directory; exit if cd failed
 cd_or_exit() {
-  if [ ! -d "$1" ]; then
-    printf "Could not cd into directory: %s\n" "$1"
-    exit
-  else
-    cd "$1"
-  fi
+	if [ ! -d "$1" ]; then
+		printf "Could not cd into directory: %s\n" "$1"
+		exit
+	else
+		cd "$1"
+	fi
 }
 
 # require that a executable be installed
 require() {
-  if [[ ! $(command -v "$1") ]]; then
-    printf "requires %s, Install that and re-run\n" "$1"
-    exit 1
-  fi
+	if [[ ! $(command -v "$1") ]]; then
+		printf "requires %s, Install that and re-run\n" "$1"
+		exit 1
+	fi
 }
 
 # clone $1 (URL) if $2 (directory) doesnt exist
 clone_if_not_exists() {
-  if [ ! -d "$2" ]; then
-    git clone "$1" "$2"
-  fi
+	if [ ! -d "$2" ]; then
+		git clone "$1" "$2"
+	fi
 }
 
 # mkdir if first arg doesnt exist
 mkdir_if_not_exists() {
-  if [ ! -d "$1" ]; then
-    mkdir -p "$1"
-  fi
+	if [ ! -d "$1" ]; then
+		mkdir -p "$1"
+	fi
 }
 
 # make sure a file exists or exit
 expect_file() {
-  if [ ! -f "$1" ]; then
-    printf "Fatal error: Expected file at %s\n" "$1"
-    exit 1
-  fi
+	if [ ! -f "$1" ]; then
+		printf "Fatal error: Expected file at %s\n" "$1"
+		exit 1
+	fi
 }
 
 require python3.7
@@ -51,7 +51,7 @@ require realpath
 require npm
 require grunt
 require forever
-require elixir  # sudo apt install erlang-inets erlang-dev elixir
+require elixir # sudo apt install erlang-inets erlang-dev elixir
 require cargo
 require sponge
 require rsync
@@ -124,7 +124,7 @@ pipenv install
 cd_or_exit "$FOREVER_WEB"
 npm install
 if [ ! -f "users.json" ]; then
-  node add_user
+	node add_user
 fi
 grunt --force
 
@@ -135,7 +135,7 @@ python3 -m pip install --user --upgrade pip
 python3 -m pip install --user jikanpy requests
 
 cd "$DOCKER_JIKAN" && docker-compose up -d # start jikan
-"$UNAP_SERVER"/cache_loop.sh once # initial call to build cache
+"$UNAP_SERVER"/cache_loop.sh once          # initial call to build cache
 
 # nginx logs
 groups | grep -q "adm" || sudo usermod -a -G adm $(whoami)
